src/Edison/Models/AccountViewModel.cs
using Edison.Lang;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Edison.Models
{
    public class RegisterViewModel
    {
        [Required]
        [StringLength(400)]
        [Display(Name = "Login", ResourceType = typeof(Account))]
        public string Name { get; set; }

        [Required]
        [StringLength(100, ErrorMessageResourceName = "Error_Password", ErrorMessageResourceType = typeof(Account), MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password", ResourceType = typeof(Account))]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "ConfirmPassword", ResourceType = typeof(Account))]
        [Compare("Password", ErrorMessageResourceName = "Error_ComparePassword", ErrorMessageResourceType = typeof(Account))]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Login", ResourceType=typeof(Account))]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password", ResourceType = typeof(Account))]
        public string Password { get; set; }

        [Display(Name = "RemeberMe", ResourceType = typeof(Account))]
        public bool RememberMe { get; set; }
    }
}

src/Edison/Controllers/AccountController.cs
using Edison.Helpers;
using Edison.Lang;
using Edison.Models;
using Edison.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Edison.DAL;
using Edison.Hub;
using Edison.Server;

namespace Edison.Controllers
{
    public class AccountController : BaseController
    {
        private readonly IUserService _userService;
        public AccountController(IUserService userService)
        {
            _userService = userService;
        }
        // GET: Account
        public ActionResult Login()
        {
            if (Request.IsAuthenticated)
            {
                LobbyServer.Instance.AddPlayer(_userService.GetUser(HttpContext.User.Identity.Name));
                return RedirectToAction("Index", "Players");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel data)
        {
            if (ModelState.IsValid)
            {
                //var user = _userService.GetUser(data.Name);
                if (_userService.IsPasswordCorrect(data.Name, data.Password))
                {
                    LobbyServer.Instance.AddPlayer(_userService.GetUser(data.Name));
                    FormsAuthentication.SetAuthCookie(data.Name, data.RememberMe);
                    return RedirectToAction("Index", "Players");
                }
                else
                {
                    ModelState.AddModelError("", Account.Error_LoginDataIncorrect);
                }
            }
            return View(data);
        }
        [HttpPost]
        public ActionResult LogOff()
        {
            LobbyServer.Instance.RemovePlayer(_userService.GetUser(HttpContext.User.Identity.Name).Id);
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterViewModel data)
        {
            if (ModelState.IsValid)
            {
                bool result = _userService.RegisterUser(data);
                if (!result)
                {
                    ModelState.AddModelError("", Account.Error_RegistringUser);
                    return View(data);
                }
            }
            else
            {
                return View(data);
            }
            return Login(new LoginViewModel { Name = data.Name, Password = data.Password });
        }
        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            // Save culture in a cookie
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return RedirectToAction("Login");
        }
    }
}

src/Edison/Controllers/BaseAsyncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Edison.Helpers;

namespace Edison.Controllers
{
    public class BaseAsyncController : AsyncController
    {
        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            string cultureName = null;

            // Attempt to read the culture cookie from Request
            HttpCookie cultureCookie = Request.Cookies["_culture"];
            if (cultureCookie != null)
                cultureName = cultureCookie.Value;
            else
                cultureName = Request.UserLanguages != null && Request.UserLanguages.Length > 0 ?
                        Request.UserLanguages[0] :  // obtain it from HTTP header AcceptLanguages
                        null;
            // Validate culture name
            cultureName = CultureHelper.GetImplementedCulture(cultureName); // This is safe

            // Modify current thread's cultures            
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(cultureName);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            return base.BeginExecuteCore(callback, state);
        }
    }
}

src/Edison/Controllers/BaseController.cs
using Edison.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Edison.Controllers
{
    public class BaseController : Controller
    {
        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            string cultureName = null;

            // Attempt to read the culture cookie from Request
            HttpCookie cultureCookie = Request.Cookies["_culture"];
            if (cultureCookie != null)
                cultureName = cultureCookie.Value;
            else
                cultureName = Request.UserLanguages != null && Request.UserLanguages.Length > 0 ?
                        Request.UserLanguages[0] :  // obtain it from HTTP header AcceptLanguages
                        null;
            // Validate culture name
            cultureName = CultureHelper.GetImplementedCulture(cultureName); // This is safe

            // Modify current thread's cultures            
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(cultureName);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            return base.BeginExecuteCore(callback, state);
        }
    }
}

src/Edison/Controllers/LobbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Edison.Server;

namespace Edison.Controllers
{
    [Authorize]
    public class LobbyController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        // GET: Lobby
        public JsonResult GetLobbies()
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public void AddLobby(LobbyType type)
        {
            
        }
    }
}

src/Edison/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Edison.Hub;
using Edison.Server;
using Edison.Service;

namespace Edison.Controllers
{
    public class PlayersController : BaseController
    {
        private readonly IUserService _userService;
        public PlayersController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View(LobbyServer.Instance.Players.ToList());
        }

        public JsonResult GetOnlinePlayers()
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

src/Edison/Views/Lobby/Index.cshtml
test

src/Edison/Views/Players/Index.cshtml
@model IEnumerable<Edison.Server.LobbyUser>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div id="players">
            @foreach (var user in Model)
            {
                <p id="@user.Id" style="margin-bottom: -2px; color: black;">
                    <strong>@user.Name</strong>
                </p>
            }
        </div>
    </div>
</div>
@section Scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var server = $.connection.lobbyHub;
            // Create a function that the hub can call back to display messages.
            server.client.LoginPlayer = function (player) {
                // Add the logged player to the page.
                $('#players').append('<p id="player' + player.Id + '" style="margin-bottom: -2px; color: black;"><strong>' + htmlEncode(player.Name) + '</strong></p>');
            };
            server.client.LogoutPlayer = function (userId) {
                // remove the logged player to the page.
                $('#player' + userId, '#players').remove();
            };
            $.connection.hub.start().done(function () {
               
            });
        });

        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

src/Edison/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Edison/Views/Shared/_Layout.cshtml
@using Edison.Lang
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container body-content">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">@(Lobby.ApplicationName)</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Lobby.GamersOnline, "Index", "Lobby")</li>
                    <li>@Html.ActionLink(Lobby.Lobby2, "Lobby", "Lobby", new { type = "x2" })</li>
                    <li>@Html.ActionLink(Lobby.Lobby4, "Lobby", "Lobby", new { type = "x4" })</li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#">@(Lobby.Hello + ", " + User.Identity.Name + "!")</a>
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
                        </ul>
                    }
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>